<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2"/>
<globals/>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="gatesphere.20220901122505.2"><vh>@file droid3scrambler.py</vh></v>
<v t="gatesphere.20220902083423.1"><vh>@edit README.md</vh></v>
</vnodes>
<tnodes>
</tnodes>
</leo_file>
